# Configuration for actions/labeler

web:
  - changed-files:
    - any-glob-to-any-file: 'apps/gs-web/**'

admin:
  - changed-files:
    - any-glob-to-any-file: 'apps/gs-admin/**'

api:
  - changed-files:
    - any-glob-to-any-file: 'apps/gs-api/**'

gateway:
  - changed-files:
    - any-glob-to-any-file: 'apps/gs-gateway/**'

control:
  - changed-files:
    - any-glob-to-any-file: 'apps/gs-control/**'

shared:
  - changed-files:
    - any-glob-to-any-file: 'packages/**'

infra:
  - changed-files:
    - any-glob-to-any-file: 'infra/**'

workflows:
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/**'

deps:
  - changed-files:
    - any-glob-to-any-file: 'package.json'
    - any-glob-to-any-file: 'pnpm-lock.yaml'
