#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import {execSync} from 'node:child_process';

const out=['from\tto\tstatus'];
const rew=[];
const assetDirs=['apps/gs-admin/src/assets','astro-goldshore'];
const exts=/\.(svg|png|jpe?g|webp|woff2?)$/i;

function slug(n){return n.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');}
function walk(d){
  if(!fs.existsSync(d)) return;
  for(const ent of fs.readdirSync(d,{withFileTypes:true})){
    const fp=path.join(d,ent.name);
    if(ent.isDirectory()) walk(fp);
    else if(exts.test(ent.name)) {
      const base=slug(path.parse(ent.name).name)+path.extname(ent.name).toLowerCase();
      const pref = /logo|brand|wordmark/i.test(ent.name)?'brand':/icon|ui|grid|star/i.test(ent.name)?'ui':'media';
      const dest=`public/assets/${pref}/${base}`;
      fs.mkdirSync(path.dirname(dest),{recursive:true});
      if(!fs.existsSync(dest)) fs.copyFileSync(fp,dest);
      out.push(`${fp}\t${dest}\tmoved-copy`);
      rew.push([fp,dest]);
    }
  }
}
assetDirs.forEach(walk);

const textFiles=execSync("rg --files apps packages src",{encoding:'utf8'}).split('\n').filter(Boolean).filter(f=>/\.(astro|tsx?|jsx?|css|md|json)$/i.test(f));
for(const f of textFiles){
  let c=fs.readFileSync(f,'utf8');
  let o=c;
  for(const [from,to] of rew){
    const b=path.basename(from);
    c=c.split(b).join('/'+to.replace(/^public\//,''));
  }
  if(c!==o){fs.writeFileSync(f,c);}
}
fs.writeFileSync('reports/migration/assets-manifest.tsv',out.join('\n')+'\n');
fs.writeFileSync('reports/migration/assets-rewrites.diff','Generated by rewrite-assets.mjs (see git diff for exact rewrites)\n');
console.log('asset manifest + rewrites complete');
