name = "gs-admin"
main = "dist/_worker.js"
compatibility_date = "2026-02-24"

[env.preview]
route = "preview.admin.goldshore.ai/*"
kv_namespaces = [{ binding = "GS_CONFIG", id = "9cc2209906a94851b704be57543987a9" }]
vars = { PREVIEW_MODE = "true", PUBLIC_API = "https://api-preview.goldshore.ai" }

[env.preview.vars]
PREVIEW_MODE = "true"
CLOUDFLARE_TEAM_DOMAIN = "goldshore.cloudflareaccess.com"

[env.production]
route = "admin.goldshore.ai/*"

[env.production.vars]
CLOUDFLARE_TEAM_DOMAIN = "goldshore.cloudflareaccess.com"

[[kv_namespaces]]
binding = "GS_CONFIG"
id = "9cc2209906a94851b704be57543987a9"
