name = "gs-admin"
main = "dist/_worker.js"
compatibility_date = "2026-02-24"

[env.preview]
route = "preview.admin.goldshore.ai/*"

[env.preview.vars]
PREVIEW_MODE = "true"
API_ORIGIN = "https://api-preview.goldshore.ai"

[[env.preview.kv_namespaces]]
binding = "GS_CONFIG"
id = "9cc2209906a94851b704be57543987a9"

[env.production]
route = "admin.goldshore.ai/*"

[env.production.vars]
API_ORIGIN = "https://api.goldshore.ai"

[[env.production.kv_namespaces]]
binding = "GS_CONFIG"
id = "9cc2209906a94851b704be57543987a9"
