name = "gs-mail"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[env.prod]
# Empty prod environment for deployment

[[kv_namespaces]]
binding = "GS_CONFIG"
id = "9cc2209906a94851b704be57543987a9"
