name = "gs-mail"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
tsconfig = "tsconfig.json"

[vars]
CLOUDFLARE_TEAM_DOMAIN = "goldshore.cloudflareaccess.com"
