name = "gs-agent"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENV = "production"

[ai]
binding = "AI"

[[queues.consumers]]
queue = "gs-jobs"

[env.dev]
name = "gs-agent-dev"
[[env.dev.queues.consumers]]
queue = "gs-jobs"
[env.dev.vars]
ENV = "development"
[env.dev.ai]
binding = "AI"


[env.prod]
name = "gs-agent"
[[env.prod.queues.consumers]]
queue = "gs-jobs"
[env.prod.vars]
ENV = "production"
[env.prod.ai]
binding = "AI"

[env.preview]
name = "gs-agent-preview"
[[env.preview.queues.consumers]]
queue = "gs-jobs"
[env.preview.vars]
ENV = "preview"
[env.preview.ai]
binding = "AI"
