name = "gs-mail"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
tsconfig = "tsconfig.json"

# Mail routing configuration (if applicable)
# [email_routing]
# ...

[env.dev]
name = "gs-mail-dev"

[env.preview]
name = "gs-mail-preview"

[env.prod]
name = "gs-mail-prod"
